package server

import (
	"net/http"
	"crypto/tls"
	"net/http/httptest"
	"testing"
)

// R05: the fallback Origin comparison must distinguish schemes on the same
// host, normalize default ports and case, and reject credential/path/query
// origins.
func TestSameOriginSchemeAware(t *testing.T) {
	get := func(target, origin string, overTLS bool) bool {
		r := httptest.NewRequest(http.MethodPost, target, nil)
		r.Host = "dash.example"
		if overTLS {
			r.TLS = new(tls.ConnectionState)
		}
		if origin != "" {
			r.Header.Set("Origin", origin)
		}
		return sameOrigin(r)
	}
	cases := []struct {
		name   string
		tls    bool
		origin string
		want   bool
	}{
		{"http same", false, "http://dash.example", true},
		{"https same", true, "https://dash.example", true},
		{"scheme mismatch", true, "http://dash.example", false},
		{"scheme mismatch reverse", false, "https://dash.example", false},
		{"explicit default port normalizes", true, "https://dash.example:443", true},
		{"host case normalizes", true, "https://DASH.example", true},
		{"explicit shared port rejected", true, "https://dash.example:80", false},
		{"other host rejected", true, "https://evil.example", false},
		{"userinfo rejected", true, "https://u:p@dash.example", false},
		{"path rejected", true, "https://dash.example/x", false},
		{"query rejected", true, "https://dash.example/?q=1", false},
		{"weird scheme rejected", true, "ftp://dash.example", false},
		{"null origin rejected", true, "null", false},
		{"no origin allowed", true, "", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := get("http://dash.example/api/deploy", tc.origin, tc.tls); got != tc.want {
				t.Fatalf("sameOrigin(tls=%v, origin=%q) = %v, want %v", tc.tls, tc.origin, got, tc.want)
			}
		})
	}
}

// R10: the hardening headers cover responses generated by the auth gate
// itself (unauthorized JSON), not only handler output.
func TestBaselineHeadersCoverGateResponses(t *testing.T) {
	s := New(Config{DataDir: t.TempDir(), NoAuth: false, Frontend: nil})
	// Force an initialized gate with users so requests hit the session
	// check rather than setup mode.
	s.gate.credMu.Lock()
	s.gate.users = map[string]*dashUser{"admin": {Username: "admin", Role: RoleAdmin, AuthEpoch: 1}}
	s.gate.setupRequired = false
	s.gate.credMu.Unlock()

	rec := httptest.NewRecorder()
	s.handler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/api/operations", nil))
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", rec.Code)
	}
	for _, header := range []string{"X-Content-Type-Options", "X-Frame-Options", "Content-Security-Policy", "Referrer-Policy"} {
		if rec.Header().Get(header) == "" {
			t.Fatalf("gate-generated response is missing %s", header)
		}
	}
}

// R04: with --no-auth, cross-origin mutations are still refused — the
// origin guard runs outside the optional auth gate.
func TestNoAuthModeStillBlocksCrossOriginMutations(t *testing.T) {
	s := New(Config{DataDir: t.TempDir(), NoAuth: true})

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, "/api/deploy", nil)
	req.Host = "dash.local"
	req.Header.Set("Origin", "https://evil.example")
	s.handler().ServeHTTP(rec, req)
	if rec.Code != http.StatusForbidden {
		t.Fatalf("cross-origin mutation must be blocked in no-auth mode, got %d", rec.Code)
	}

	rec2 := httptest.NewRecorder()
	req2 := httptest.NewRequest(http.MethodPost, "/api/deploy", nil)
	req2.Host = "dash.local"
	req2.Header.Set("Origin", "http://dash.local")
	s.handler().ServeHTTP(rec2, req2)
	if rec2.Code == http.StatusForbidden {
		t.Fatalf("same-origin mutation must pass the origin guard, got %d", rec2.Code)
	}
}
